---
title: "Case Study B - Pain Relief Medication"
author: "Oumaima Al Qoh, Francisco Arrieta, Lucia Camenisch, Manuela Giansante, Emily Schmidt, Camille Beatrice Valera"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    toc: true # creating a table of contents (toc)
    toc_float: 
      collapsed: false # toc does not collapse and is shown as a sidebar (toc_float)
    number_sections: true # document sections are numbered
    theme: cosmo
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, fig.align = "center")
```

```{r packages}
library(data.table)
library(ggplot2)
```

```{r data}
pain <- fread("Bpain.csv")
```

```{r removing useless cols}
pain <- pain[, -c(1,6)]
```

```{r prop dummy}
pain <- pain[, Prop_dummy  := ifelse(Prop >= 0.5, "Effective", "Ineffective")]
```

```{r}
pain_melt <- pain[Set %in% c("A", "B"),]
pain_melt <- pain_melt[, c(2,3,5)]
pain_melt <- melt(pain_melt, id.vars = "Prop")
pain_melt <- pain_melt[c(1:8, 22:26), ]
```

```{r}
ggplot(data = pain_melt, aes(x = value, y = Prop)) +
  geom_line(color = "darkgray") +
  geom_point() +
  geom_hline(yintercept = 0.5, color = "red", linetype = "dashed") +
  facet_wrap(~ variable, scales = "free_x") +
  scale_x_continuous(breaks = 1:16) +
  scale_y_continuous(breaks = seq(0,1,0.1)) +
  theme_light(base_size = 15) +
  labs(title = "Dose-response curves for Marijuana and Morphine",
       x = "Dosage in mg/kg",
       y = "Proportion of mice responding")
ggsave("dose-response.png")
```


```{r}
ggplot(data = pain_melt, aes(x = value, y = Prop)) +
  geom_col(color = "black", fill = "white") +
  facet_wrap(~ variable, scales = "free_x") +
  scale_x_continuous(breaks = 1:16) +
  scale_y_continuous(breaks = seq(0,1,0.1)) +
  theme_light(base_size = 15) +
  labs(title = "Proportion of mice responding per dosage of drug",
       x = "Dosage in mg/kg",
       y = "Proportion of mice responding")
ggsave("drugs_barplots.png")
```


```{r}
ggplot(data = pain_melt, aes(x = Prop, y = value)) +
  geom_point() +
  facet_wrap(~ variable, nrow = 2) +
  scale_x_continuous(breaks = seq(0, 1, 0.1)) +
  scale_y_continuous(breaks = seq(0,16,4)) +
  theme_light(base_size = 15) +
  labs(title = "Dosages of Marijuana and Morphine vs Efficacy",
       x = "Efficacy",
       y = "Dosage in mg/kg")
  ggsave("potency_ratio.png")
```



```{r}
ggplot(pain[Set %in% "B",], aes(x = Marijuana, y = Morphine)) +
  geom_point(size = 2) +
  coord_equal() +
  theme_light(base_size = 15) +
  scale_x_continuous(breaks = c(0:16)) +
  scale_y_continuous(breaks = c(0:8), limits = c(0,8)) +
  theme(axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()) +
  labs(title = "Dosages of Marijuana",
       x = "Marijuana dosage in mg/kg")
ggsave("iso1.png")
```

```{r}
ggplot(pain[Set %in% "B",], aes(x = Marijuana, y = Morphine, color = Prop_dummy)) +
  geom_point(size = 2) +
  coord_equal() +
  theme_light(base_size = 15) +
  scale_x_continuous(breaks = c(0:16)) +
  scale_y_continuous(breaks = c(0:8), limits = c(0,8)) +
  theme(axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()) +
  labs(title = "Dosages of Marijuana",
       x = "Marijuana dosage in mg/kg",
       color = "Efficacy \nof dosages")
ggsave("iso2.png")
```

```{r}
ggplot(pain[Set %in% "B",], aes(x = Marijuana, y = Morphine, color = Prop_dummy)) +
  geom_point(size = 2) +
  geom_point(data = pain[Set %in% "A",], mapping = aes(x = Marijuana, y = Morphine), size = 2, color = "black") +
  coord_equal() +
  theme_light(base_size = 15) +
  scale_x_continuous(breaks = c(0:16)) +
  scale_y_continuous(breaks = c(0:8), limits = c(0,8)) +
  labs(title = "Dosages of Marijuana and Morphine",
       x = "Marijuana dosage in mg/kg",
       y = "Morphine dosage in mg/kg",
       color = "Efficacy \nof dosages")
ggsave("iso3.png")
```



```{r}
ggplot(pain[Set %in% c("A", "B"),], aes(x = Marijuana, y = Morphine, color = Prop_dummy)) +
  geom_point(size = 2) +
  coord_equal() +
  theme_light(base_size = 15) +
  scale_x_continuous(breaks = c(0:16)) +
  scale_y_continuous(breaks = c(0:8), limits = c(0,8)) +
  labs(title = "Dosages of Marijuana and Morphine",
       x = "Marijuana dosage in mg/kg",
       y = "Morphine dosage in mg/kg",
       color = "Efficacy \nof dosages")
ggsave("iso4.png")
```

```{r}
ggplot(pain[Set %in% c("O", "A", "B"),], aes(x = Marijuana, y = Morphine, color = Prop_dummy)) +
  geom_point(size = 2) +
  coord_equal() +
  theme_light(base_size = 15) +
  scale_x_continuous(breaks = c(0:16)) +
  scale_y_continuous(breaks = c(0:8), limits = c(0,8)) +
  labs(title = "Dosages of Marijuana and Morphine",
       x = "Marijuana dosage in mg/kg",
       y = "Morphine dosage in mg/kg",
       color = "Efficacy \nof dosages")
ggsave("iso5.png")
```

```{r}
ggplot(pain[Set %in% c("O", "A", "B"),], aes(x = Marijuana, y = Morphine, color = Prop_dummy)) +
  geom_point(size = 2) +
  geom_point(data = pain[Set %in% "AB",], mapping = aes(x = Marijuana, y = Morphine), size = 2, color = "black") +
  coord_equal() +
  theme_light(base_size = 15) +
  scale_x_continuous(breaks = c(0:16)) +
  scale_y_continuous(breaks = c(0:8), limits = c(0,8)) +
  labs(title = "Dosages of Marijuana and Morphine",
       x = "Marijuana dosage in mg/kg",
       y = "Morphine dosage in mg/kg",
       color = "Efficacy \nof dosages")
ggsave("iso6.png")
```

```{r}
ggplot(pain, aes(x = Marijuana, y = Morphine, color = Prop_dummy)) +
  geom_point(size = 2) +
  coord_equal() +
  theme_light(base_size = 15) +
  scale_x_continuous(breaks = c(0:16)) +
  scale_y_continuous(breaks = c(0:8)) +
  labs(title = "Dosages of Marijuana and Morphine",
       x = "Marijuana dosage in mg/kg",
       y = "Morphine dosage in mg/kg",
       color = "Efficacy \nof dosages")
ggsave("dosages_plot.png")
```

```{r}
isobole_coords <- data.table("Marijuana" = c(0, 3), "Morphine" = c(4.5, 0))

ggplot(pain, aes(x = Marijuana, y = Morphine, color = Prop_dummy)) +
  geom_point(size = 2) +
  coord_equal() +
  geom_abline(intercept = 4.5, slope = -4.5/3) +
  geom_point(data = isobole_coords,
             aes(x = Marijuana, y = Morphine, fill = "Theoretical \n50% effect"),
             color = "black",
             pch = 24,
             size = 3) +
  theme_light(base_size = 15) +
  scale_x_continuous(breaks = c(0:16)) +
  scale_y_continuous(breaks = c(0:8)) +
  labs(title = "Dosages of Marijuana and Morphine with Isobole",
       x = "Marijuana dosage in mg/kg",
       y = "Morphine dosage in mg/kg",
       color = "Efficacy \nof dosages",
       fill = "")
ggsave("isobole.png")
```

```{r}
ggplot(pain, aes(x = Marijuana, y = Morphine, color = Prop_dummy)) +
  geom_abline(intercept = 4, slope = -4/2, color = "darkgray", linetype = "dashed") +
  geom_abline(intercept = 5, slope = -5/4, color = "darkgray", linetype = "dashed") +
  geom_point(size = 2) +
  coord_equal() +
  geom_abline(intercept = 4.5, slope = -4.5/3) +
  geom_point(data = isobole_coords,
             aes(x = Marijuana, y = Morphine, fill = "Theoretical \n50% effect"),
             color = "black",
             pch = 24,
             size = 3) +
  theme_light(base_size = 15) +
  scale_x_continuous(breaks = c(0:16)) +
  scale_y_continuous(breaks = c(0:8)) +
  labs(title = "Dosages of Marijuana and Morphine with Isobole",
       x = "Marijuana dosage in mg/kg",
       y = "Morphine dosage in mg/kg",
       color = "Efficacy \nof dosages",
       fill = "")
ggsave("isobole-vary.png")
```


```{r}
ggplot(pain, aes(x = Marijuana, y = Morphine, color = Prop_dummy)) +
    geom_ribbon(data = isobole_coords,
                aes(ymin = c(0, 0), ymax = Morphine),
                color = NA,
                fill = "cyan",
                alpha = 0.3) +
      geom_ribbon(data = isobole_coords,
                  aes(ymax = c(8, 8), ymin = Morphine),
                  color = NA,
                  fill = "red",
                  alpha = 0.3) +
        geom_ribbon(data = pain[c(14,20),],
                    mapping = aes(xmin = 3, xmax = 16, ymin = 0, ymax = 8),
                    color = NA,
                    fill = "red",
                    alpha = 0.3) +
  geom_point(size = 2) +
  coord_equal() +
  geom_abline(intercept = 4.5, slope = -4.5/3) +
  geom_point(data = isobole_coords,
             aes(x = Marijuana, y = Morphine, fill = "Theoretical \n50% effect"),
             color = "black",
             pch = 24,
             size = 3) +
  theme_light(base_size = 15) +
  scale_x_continuous(breaks = c(0:16)) +
  scale_y_continuous(breaks = c(0:8)) +
  labs(title = "Dosages of Marijuana and Morphine with Isobole",
       x = "Marijuana dosage in mg/kg",
       y = "Morphine dosage in mg/kg",
       color = "Efficacy \nof dosages",
       fill = "")
ggsave("isobole_with_areas.png")
```



```{r}
ggplot(pain, aes(x = Marijuana, y = Morphine, color = Prop_dummy)) +
  geom_point(size = 2) +
  coord_equal() +
  geom_point(mapping = aes(x = 2.1, y = 0), color = "black", fill = "red", size = 3, pch = 22) +
  geom_abline(intercept = 5, slope = -5/2.1) +
  theme_light(base_size = 15) +
  scale_x_continuous(breaks = c(0:16)) +
  scale_y_continuous(breaks = c(0:8)) +
  labs(title = "Dosages of Marijuana and Morphine with Isobole",
       x = "Marijuana dosage in mg/kg",
       y = "Morphine dosage in mg/kg",
       color = "Efficacy \nof dosages")
```



